name: build_and_test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Allows manual running
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # check-out the repository
      - name: Build
        run: echo Hello, world!
      - name: Test
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
