name: build-and-test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Allows manual running
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # check-out the repository
      - name: Build Docker image
        run: |
          docker build . -f Dockerfile -t mguim
          sudo apt-get install wget
      - name: Test microgridup_gui.py server runs and returns successful response
        run: |
          docker run -d -p 5000:5000 --name mgucont mguim
          sleep 10
          wget localhost:5000
      - name: Run microgridup_gen_mgs._tests
        run: |
          docker run mguim -c "import microgridup_gen_mgs; microgridup_gen_mgs._tests()"
      - name: Run microgridup_design._tests
        run: |
          docker run mguim -c "import microgridup_design; microgridup_design._tests()"
      - name: Run microgridup_hosting_cap._tests
        run: |
          docker run mguim -c "import microgridup_hosting_cap; microgridup_hosting_cap._tests()"
      - name: Run microgridup_control._tests
        run: |
          docker run mguim -c "import microgridup_control; microgridup_control._tests()"
      - name: Run microgridup_resilience._tests
        run: |
          docker run mguim -c "import microgridup_resilience; microgridup_resilience._tests()"
      - name: Run microgridup_gui._tests
        run: |
          docker run mguim -c "import microgridup_gui; microgridup_gui._tests()"
      - name: Run tests_backend_full.py
        run: |
          docker run mguim tests_backend_full.py