name: build-and-test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Allows manual running
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # check-out the repository
      - name: Build With Docker
        run: |
          docker build . -f Dockerfile -t mguim
          sudo apt-get install wget
      - name: Test
        run: |
          docker run -d -p 5000:5000 --name mgucont mguim
          sleep 10
          wget localhost:5000
